name: 'dbt_debug'
version: '1.0.0'

profile: 'dbt_debug'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: [macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_debug:
      +materialized: view

on-run-start:
  - "{{ log('Run type: ' + flags.WHICH, info=True) }}"
